CREATE DATABASE DB_LEILAO

CREATE TABLE TB_MATERIAL(
	CODIGO INT IDENTITY(1,1) PRIMARY KEY,
	URL_FOTO VARCHAR(MAX),
	DESCRICAO VARCHAR(MAX),
	LANCE_INICIAL VARCHAR(20),
	MAIOR_LANCE VARCHAR(20),
	QTD_LANCE INT

)
select * from TB_MATERIAL