//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MATERIAL
    {
        public int CODIGO { get; set; }
        public string URL_FOTO { get; set; }
        public string DESCRICAO { get; set; }
        public string LANCE_INICIAL { get; set; }
        public string MAIOR_LANCE { get; set; }
        public Nullable<int> QTD_LANCE { get; set; }
    }
}
